detect_field_num = 4
[[area]]
"場所" = "5階"
"利用者" = "E:\\project\\smoking-area-count\\e2e_test\\tmp.csv"
"待ち人数" = "E:\\project\\smoking-area-count\\e2e_test\\tmp.csv"
"定員上限" = 5

[[area]]
"場所" = "9階"
"利用者" = "E:\\project\\smoking-area-count\\e2e_test\\tmp1.csv"
"待ち人数" = "E:\\project\\smoking-area-count\\e2e_test\\fuga.csv"
"定員上限" = 3

[[area]]
"場所" = "11階"
"利用者" = ""
"待ち人数" = ""
"定員上限" = 5

