# logファイルの場所を「絶対パス」で記載
log_csv_file = [
  'E:\project\rework\smoking-area-count\backend\src\tests\test_file\video_source.csv'
]

# 検知数が格納されているカラムの列数
detect_field_num = 4

# 定員上限数
[capacity_limit]
5階 = 7
9階 = 5
11階 = 10