# logファイルの場所を「絶対パス」で記載
log_csv_file = 'E:\project\rework\smoking-area-count\backend\src\tests\test_file\video_source.csv'

# 検知数が格納されているカラムのヘッダー名
detect_field_name = ' 検知数'

# 定員上限数
capacity_limit = 7